variable "prefix" {
  description = "Prefix for resources"
  type        = string
  default     = ""
  validation {
    condition     = length(var.prefix) <= 37
    error_message = "Name Prefix may not be longer than 37 characters."
  }
}

variable "suffix" {
  description = "Suffix for resources"
  type        = string
  default     = ""
}

variable "users" {
  description = "List of users to change passwords for password lambda function"
  type        = list(string)
}

variable "rotation_tag_key" {
  description = "Tag key to identify resources that need password rotation"
  type        = string
  default     = "Password-Rotation"
}

variable "rotation_tag_value" {
  description = "Tag value to identify resources that need password rotation"
  type        = string
  default     = "enabled"
}

variable "lambda_additional_policy_statements" {
  description = "Additional policy statements to add to the lambda function policy, will be merged in"
  type        = any
  default     = {}
}

variable "notification_webhook_url" {
  description = "Webhook URL for notifications"
  type        = string
  default     = null
}

variable "region" {
  description = "AWS Region"
  type        = string
}

variable "description" {
  description = "Description of the lambda function"
  type        = string
  default     = "Lambda Function that performs some predefined action"
}

variable "handler" {
  description = "Handler for the lambda function"
  type        = string
  default     = "lambda_function.lambda_handler"
}

variable "runtime" {
  description = "Runtime for the lambda function"
  type        = string
  default     = "python3.9"
}

variable "timeout" {
  description = "Timeout for the lambda function"
  type        = number
  default     = 900
}

variable "tags" {
  description = "A map of tags to apply to all resources"
  type        = map(string)
  default     = {}
}

############################################################################
##################### Secrets Manager ############################
############################################################################

variable "secrets_manager_secret_name" {
  description = "Name of the secret in Secrets Manager"
  type        = string
  default     = null
}

variable "secrets_manager_secret_name_prefix" {
  description = "Prefix for the secret in Secrets Manager"
  type        = string
  default     = "password-rotation-"
}

variable "recovery_window_in_days" {
  description = "The number of days that Secrets Manager waits before it can delete the secret"
  type        = number
  default     = 7
}

variable "secrets_manager_secret_description" {
  description = "Description of the secret in Secrets Manager"
  type        = string
  default     = "Rotated Secrets Manager secret"
}

variable "secrets_manager_additional_policy_statements" {
  description = "Additional policy statements to add to the Secrets Manager policy, will be merged in"
  type        = any
  default     = {}
}

variable "initial_secret_json_value" {
  description = "Initial secret value to store in Secrets Manager, provided as a JSON map object, generated by random_password if not provided"
  type        = string
  default     = ""
}

variable "rotation_rules" {
  description = "Rotation rules for the secret"
  type        = map(any)
  default = {
    schedule_expression = "rate(30 days)"
  }
}

variable "allow_current_context_to_access_secret" {
  description = "Allow the current user to access the secret"
  type        = bool
  default     = true
}
